version: "3.9"
services:
  db:
    image: postgres:15
    container_name: collab_db
    environment:
      POSTGRES_USER: collab
      POSTGRES_PASSWORD: collab123
      POSTGRES_DB: collabdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: