// Code generated by MockGen. DO NOT EDIT.
// Source: live-collab-api/internal/auth (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/documents/mocks/auth_mocks.go -package=mocks -mock_names=Service=MockAuthService live-collab-api/internal/auth Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of Service interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// GetUserIDFromGinContext mocks base method.
func (m *MockAuthService) GetUserIDFromGinContext(c *gin.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDFromGinContext", c)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDFromGinContext indicates an expected call of GetUserIDFromGinContext.
func (mr *MockAuthServiceMockRecorder) GetUserIDFromGinContext(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDFromGinContext", reflect.TypeOf((*MockAuthService)(nil).GetUserIDFromGinContext), c)
}
