// Code generated by MockGen. DO NOT EDIT.
// Source: live-collab-api/internal/documents (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/documents/mocks/mocks.go -package=mocks live-collab-api/internal/documents Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	documents "live-collab-api/internal/documents"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateDocument mocks base method.
func (m *MockService) CreateDocument(title string, ownerId int) (*documents.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDocument", title, ownerId)
	ret0, _ := ret[0].(*documents.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDocument indicates an expected call of CreateDocument.
func (mr *MockServiceMockRecorder) CreateDocument(title, ownerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDocument", reflect.TypeOf((*MockService)(nil).CreateDocument), title, ownerId)
}

// DeleteDocument mocks base method.
func (m *MockService) DeleteDocument(documentId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDocument", documentId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDocument indicates an expected call of DeleteDocument.
func (mr *MockServiceMockRecorder) DeleteDocument(documentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDocument", reflect.TypeOf((*MockService)(nil).DeleteDocument), documentId)
}

// GetDocument mocks base method.
func (m *MockService) GetDocument(documentId int) (*documents.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocument", documentId)
	ret0, _ := ret[0].(*documents.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocument indicates an expected call of GetDocument.
func (mr *MockServiceMockRecorder) GetDocument(documentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocument", reflect.TypeOf((*MockService)(nil).GetDocument), documentId)
}

// GetDocumentEvents mocks base method.
func (m *MockService) GetDocumentEvents(documentId, limit int) ([]documents.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocumentEvents", documentId, limit)
	ret0, _ := ret[0].([]documents.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocumentEvents indicates an expected call of GetDocumentEvents.
func (mr *MockServiceMockRecorder) GetDocumentEvents(documentId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocumentEvents", reflect.TypeOf((*MockService)(nil).GetDocumentEvents), documentId, limit)
}

// GetUserDocuments mocks base method.
func (m *MockService) GetUserDocuments(userId int) ([]documents.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDocuments", userId)
	ret0, _ := ret[0].([]documents.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDocuments indicates an expected call of GetUserDocuments.
func (mr *MockServiceMockRecorder) GetUserDocuments(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDocuments", reflect.TypeOf((*MockService)(nil).GetUserDocuments), userId)
}

// HasDocumentAccess mocks base method.
func (m *MockService) HasDocumentAccess(userId, DocumentId int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDocumentAccess", userId, DocumentId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasDocumentAccess indicates an expected call of HasDocumentAccess.
func (mr *MockServiceMockRecorder) HasDocumentAccess(userId, DocumentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDocumentAccess", reflect.TypeOf((*MockService)(nil).HasDocumentAccess), userId, DocumentId)
}

// UpdateDocumentTitle mocks base method.
func (m *MockService) UpdateDocumentTitle(documentId int, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDocumentTitle", documentId, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDocumentTitle indicates an expected call of UpdateDocumentTitle.
func (mr *MockServiceMockRecorder) UpdateDocumentTitle(documentId, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDocumentTitle", reflect.TypeOf((*MockService)(nil).UpdateDocumentTitle), documentId, title)
}
